### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [LoganBarnes/LightBender#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118532946-19b33480-b77a-11eb-9969-6fbbc3fc86fe.png)

thank you  
best regards to you  
William

**Comment by LoganBarnes** [comment]
It looks like you haven't checked out the submodules. If you follow along in the [README](https://github.com/LoganBarnes/LightBender#download) it should contain all the commands to help you build and run the project. You will probably also need to download OptiX from [here](https://developer.nvidia.com/designworks/optix/downloads/legacy) (if you don't already have it). I just tested out the repo with OptiX 6.5 and it seems to build and run. I doubt OptiX 7 will work since there were significant changes.

If the instructions in the README aren't clear or you are still having trouble let me know.

**Comment by LoganBarnes** [comment]
Actually I take that back. OptiX 5 is probably the version I used when developing this. It compiles with a bunch of deprecation warnings if you're using a modern CUDA but it should still work. Optix 6 causes some round objects to become cubes:

![cube-lights](https://user-images.githubusercontent.com/3151827/118740395-aaa21280-b843-11eb-9a5a-2bb0c96e5f3c.png)

Optix 5 seems to work as expected:

![sphere-lights](https://user-images.githubusercontent.com/3151827/118740433-c9a0a480-b843-11eb-8d6c-790f9b1e5a46.png)

**Comment by LoganBarnes** [comment]
I will assume this has been resolved
